name: CI Pipeline

on:
  push:
    branches:
      - test
      - main
      - develop
  pull_request:
    branches:
      - test
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Validate project
        run: mvn validate

      - name: Run linting (Checkstyle)
        run: mvn checkstyle:check

      - name: Run tests
        run: mvn test

  build:
    needs: test
    if: github.ref_name == 'main' || github.ref_name == 'test'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Set environment variables based on branch
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "PROFILE=prod" >> $GITHUB_ENV
            echo "DOCKER_TAG=latest" >> $GITHUB_ENV
            echo "SPRING_DATASOURCE_URL=${{ secrets.SPRING_PROD_DB_URL }}" >> $GITHUB_ENV
            echo "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_PROD_DB_USER }}" >> $GITHUB_ENV
            echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_PROD_DB_PASSWORD }}" >> $GITHUB_ENV
            echo "ADMIN_USERNAME=${{ secrets.PROD_ADMIN_USERNAME }}" >> $GITHUB_ENV
            echo "ADMIN_PASSWORD=${{ secrets.PROD_ADMIN_PASSWORD }}" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "test" ]; then
            echo "PROFILE=test" >> $GITHUB_ENV
            echo "DOCKER_TAG=latest" >> $GITHUB_ENV
            echo "SPRING_DATASOURCE_URL=${{ secrets.SPRING_TEST_DB_URL }}" >> $GITHUB_ENV
            echo "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_TEST_DB_USER }}" >> $GITHUB_ENV
            echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_TEST_DB_PASSWORD }}" >> $GITHUB_ENV
            echo "ADMIN_USERNAME=${{ secrets.TEST_ADMIN_USERNAME }}" >> $GITHUB_ENV
            echo "ADMIN_PASSWORD=${{ secrets.TEST_ADMIN_PASSWORD }}" >> $GITHUB_ENV
          fi

      - name: Build frontend assets
        run: mvn vaadin:build-frontend -P$PROFILE

      - name: Build project for $PROFILE
        run: mvn package -DskipTests -P$PROFILE

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: accounting-app-${{ env.PROFILE }}
          path: target/*.jar

      # Docker Build & Push Steps
      - name: Log in to private Docker registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: |
          JAR_FILE=$(ls target/*.jar | head -n 1)
          docker build -t ${{ secrets.REGISTRY_URL }}/accounting-app/test:${{ env.DOCKER_TAG }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.REGISTRY_URL }}/accounting-app/prod:${{ env.DOCKER_TAG }}

      - name: Logout from Docker registry
        run: docker logout ${{ secrets.REGISTRY_URL }}
