name: Increment Version in Develop

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  increment-version:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop' && github.event.pull_request.head.ref == 'test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Increment version in develop
        run: |
          VERSION=$(grep -oP '(?<=<version>)[0-9]+\.[0-9]+\.[0-9]+' pom.xml)
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH-SNAPSHOT"
          sed -i "s/<version>$VERSION<\/version>/<version>$NEW_VERSION<\/version>/g" pom.xml
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add pom.xml
          git commit -m "Increment version to $NEW_VERSION [ci skip]" || exit 0
          git push origin develop

      - name: Merge test back into develop
        run: |
          git checkout develop
          git pull origin develop
          git merge --no-ff test -m "Auto-merge test into develop after version increment [ci skip]"
          git push origin develop
