name: Update Version on Test

on:
  push:
    branches:
      - test

jobs:
  update-version-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update version in pom.xml
        run: |
          VERSION=$(grep -oP '(?<=<version>)[0-9]+\.[0-9]+\.[0-9]+(?=-SNAPSHOT)' pom.xml | head -n 1)
          
          sed -i "s/<version>$VERSION-SNAPSHOT<\/version>/<version>$VERSION<\/version>/" pom.xml

          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Update version for test release: $NEW_VERSION"
          
          git push

      - name: Merge test back into develop
        run: |
          git fetch --all
          git checkout develop
          git pull origin develop
          git merge --no-ff test -m "Auto-merge test into develop after removing -SNAPSHOT [ci skip]"
          git push origin develop
